In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/multinominallogistisregression/PertanianUAS.csv


In [2]:
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv('../input/multinominallogistisregression/PertanianUAS.csv')
df.head()

DER  Operating Profit Margin  Sales Growth  Return On Asset  Category
0  0.135154                 0.135154      1.293241         0.064848         1
1  0.758859                -0.064557      0.834610        -0.064974         1
2  0.395062                 0.236027      1.625789         0.061328         2
3  0.000624                 0.227386      0.797727         0.119392         1
4  1.239184                -2.007213      1.451510        -0.059932         4

In [4]:
np.asarray(df)

array([[ 1.35154326e-01,  1.35154326e-01,  1.29324147e+00,
         6.48477330e-02,  1.00000000e+00],
       [ 7.58859160e-01, -6.45565480e-02,  8.34610166e-01,
        -6.49736420e-02,  1.00000000e+00],
       [ 3.95062270e-01,  2.36026568e-01,  1.62578915e+00,
         6.13284300e-02,  2.00000000e+00],
       [ 6.23580000e-04,  2.27386464e-01,  7.97726643e-01,
         1.19392284e-01,  1.00000000e+00],
       [ 1.23918365e+00, -2.00721268e+00,  1.45150996e+00,
        -5.99320140e-02,  4.00000000e+00],
       [ 3.51720847e+00, -4.12206492e-01,  1.33641854e+00,
        -1.16518174e-01,  1.00000000e+00],
       [ 5.08335265e+00,  3.31290314e-01,  1.05542852e+00,
         4.05886354e-01,  2.00000000e+00],
       [ 7.55672046e-01,  1.93574141e-01,  1.06352921e+00,
         5.30297930e-02,  4.00000000e+00],
       [ 6.24000055e-01, -3.19872460e-02,  1.05681644e+00,
        -2.64757790e-02,  1.00000000e+00],
       [ 1.06140122e+01,  5.25930500e-03,  6.37814498e-01,
        -5.52244650e-02

In [5]:
import statsmodels.api as sm

In [6]:
x = df.drop('Category', axis=1)
x.head()

DER  Operating Profit Margin  Sales Growth  Return On Asset
0  0.135154                 0.135154      1.293241         0.064848
1  0.758859                -0.064557      0.834610        -0.064974
2  0.395062                 0.236027      1.625789         0.061328
3  0.000624                 0.227386      0.797727         0.119392
4  1.239184                -2.007213      1.451510        -0.059932

In [7]:
y = df['Category']
y.head()

0    1
1    1
2    2
3    1
4    4
Name: Category, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [9]:
x_train_sm = sm.add_constant(x_train)
x_train_sm

const        DER  Operating Profit Margin  Sales Growth  Return On Asset
16    1.0   1.026782                 0.458206      1.297166         0.109419
7     1.0   0.755672                 0.193574      1.063529         0.053030
3     1.0   0.000624                 0.227386      0.797727         0.119392
6     1.0   5.083353                 0.331290      1.055429         0.405886
0     1.0   0.135154                 0.135154      1.293241         0.064848
14    1.0   0.697246                 0.279514      1.491136         0.082254
1     1.0   0.758859                -0.064557      0.834610        -0.064974
4     1.0   1.239184                -2.007213      1.451510        -0.059932
9     1.0  10.614012                 0.005259      0.637814        -0.055224
11    1.0   3.570709                -0.980925      0.977537        -0.178472
5     1.0   3.517208                -0.412206      1.336419        -0.116518
8     1.0   0.624000                -0.031987      1.056816        -0.026476
2     1.0   0.395062                 0.236027      1.625789         0.061328
18    1.0  -1.322743                 0.195796      1.263455        -0.003921
12    1.0   1.192419                 0.023986      1.780840         0.043147

In [10]:
#logit_mod = sm.Logit(y_train, x_train_sm
                     
mnlogit_mod = sm.MNLogit(y_train, x_train_sm)
mnlogit_fit = mnlogit_mod.fit()

         Current function value: nan
         Iterations: 35


/opt/conda/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:2331: RuntimeWarning: divide by zero encountered in log
  logprob = np.log(self.cdf(np.dot(self.exog,params)))
/opt/conda/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:2332: RuntimeWarning: invalid value encountered in multiply
  return np.sum(d * logprob)
/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)


In [11]:
print (mnlogit_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:               Category   No. Observations:                   15
Model:                        MNLogit   Df Residuals:                        0
Method:                           MLE   Df Model:                           12
Date:                Wed, 06 Jul 2022   Pseudo R-squ.:                     nan
Time:                        09:25:50   Log-Likelihood:                    nan
converged:                      False   LL-Null:                       -17.054
Covariance Type:            nonrobust   LLR p-value:                       nan
             Category=2       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                    -339.4759    3.4e+05     -0.001      0.999   -6.66e+05    6.65e+05
DER                        11.9331   3.58e+04      0.000      1.000   -7.02e+04    7.02e+04


/opt/conda/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py:4247: RuntimeWarning: invalid value encountered in sqrt
  bse = np.sqrt(np.diag(self.cov_params()))


In [12]:
model = LogisticRegression(multi_class='auto')
model.fit(x_train, y_train)

LogisticRegression()

In [13]:
model.predict_proba(x_test)[0:5]

array([[0.53737913, 0.3093687 , 0.03639469, 0.11685749],
       [0.35838901, 0.52357939, 0.03550296, 0.08252864],
       [0.5636841 , 0.29284703, 0.02968732, 0.11378156],
       [0.55827308, 0.30827238, 0.04433769, 0.08911685]])

In [14]:
predictions = model.predict(x_test)
predictions

array([1, 2, 1, 1])

In [15]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3
           2       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1

    accuracy                           0.75         4
   macro avg       0.33      0.33      0.33         4
weighted avg       0.75      0.75      0.75         4



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1

In [16]:
print(accuracy_score(y_test, predictions))

0.75
